### ISSUE TITLE
Sass: Nest Pseudo-Elements

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/CSS-Guidelines#17]
The guidelines don't mention nesting of pseudo-elements and pseudo-selectors:

``` scss
.selector {
  &:after {
    ...
  }

  &:before {
    ...
  }

  &:hover {
    ...
  }

  // etc, etc, etc
}
```

These should be nested.

Before Closing Issue:
- [x] Response from @jstoutenburg
- [x] Response from @janiv
- [x] Response from @kbratko
- [x] Response from @jspencerDDM
- [ ] Consensus or Decision
- [ ] Pull request or other action if necessary

**Comment by rsahlstrom** [comment]
Agreed.

With this, I'd also like to see modifier classes that modify child elements nested within the child element as well.

For example:

``` scss
.dropdown__body {
  display: none;

  .dropdown--open > & {
    display: block;
  }
}
```

 @deseretdigital-ui/front-end-developers
