### ISSUE TITLE
CSS Character Code in Content

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/CSS-Guidelines#24]
I'd like to add to the guidelines that we should use character codes instead of copy/paste the actual character. It seems that the character code is more reliable to render correctly.

So I'd like to use the character code, with a comment explaining what it is.

So this is wrong:

``` css
  .forward-link:after {
    content: " »";
  }

  .backward-link:before {
    content: "« ";
  }
```

This is correct:

``` css
  .forward-link:after {
    content: " \00bb"; /* &raquo; */
  }

  .backward-link:before {
    content: "\00ab  "; /* &laquo; */
  }
```

It also seems that two spaces are needed after a character code. A single space gets trimmed out. But only one space is needed before a character code.

**Before Closing Issue:**
- [x] Response from @jstoutenburg
- [ ] Response from @janiv
- [ ] Response from @kbratko
- [ ] Response from @jspencerDDM
- [x] Response from @hhatfield
- [ ] Consensus or Decision
- [ ] Pull request or other action if necessary
